### PR TITLE
Ability to select region on installation

### PR DESCRIPTION
**Pull request by kaanklky**
Hi,
First of all, thank you for this little helper script project. I added new function to script that prompt a selection to user to select region for installation.

### CODE REVIEW

**Comment by Nefelim4ag** [comment]
@kyechou, get eye on that plz, thx

**Comment by kyechou** [comment]
Hi all,
Sorry for the late reply. It seems great. I tested it on a new machine and everything works fine. Though I've only tested this for the "NA" region.

**Comment by kaanklky** [comment]
Hi @kyechou,
Thank you for your inspection, meanwhile I added Latin America North, Latin America South & Oceania servers to the list.

**Comment by kaanklky** [comment]
Aaand I found the link for Korea too. :) It would be great if you can test it for Korea too since I don't have a Linux system with Wine for now.

**Pull request merged**
